version: '3'
services:
  eustr-addon:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      # Aggiungi la tua chiave TMDB qui o tramite un file .env
      - TMDB_API_KEY=${TMDB_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/manifest.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
