version: '3'
services:
  eustr-addon:
    build: .
    ports:
      - "5555:5555"
    environment:
      - PORT=5555
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/manifest.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
